title: MMI Bordeaux
url: https://www.mmibordeaux.com

plugins:
  - jekyll-datapage-generator

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "competencies"
    values:
      layout: "competency"
  -
    scope:
      path: ""
      type: "paths"
    values:
      layout: "path"
  -
    scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"

collections:
  competencies:
    output: true
    permalink: /competences/:name
    order:
      - comprendre.html
      - concevoir.html
      - exprimer.html
      - developper.html
      - entrependre.html
  paths:
    output: true
    permalink: /parcours/:name
    order:
      - strategie-de-communication-numerique-et-design-d-experience.html
      - creation-numerique.html
      - developpement-web-et-dispositifs-interactifs.html
  workshops:
    output: true
    permalink: /ateliers/:name

page_gen:
  - data: bibliography
    name: slug
    title: title
    template: bibliography
    dir: bibliographie
