url: https://www.mmibordeaux.com
title: MMI Bordeaux
description: BUT (Bachelor Universitaire de Technologie) MMI (Métiers du Multimedia & de l'Internet) à Bordeaux
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  load_paths:
    - bower_components/
incremental: true
exclude: ['gulpfile.js', 'Gemfile', 'Gemfile.lock']

collections:
  works:
    output: true
    permalink: /portfolio/:name/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work

paginate: 4
paginate_path: "/blog/page/:num"

# This is the place to set up the commenting system
# disqus:
#   shortname: your-disqus-shortname

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
