[[redirects]]
  from = "/but-mmi.html"
  to = "/candidatures"
  status = 301
  force = false
[[redirects]]
  from = "/equipe.html"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/entreprises.html"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/blog/*"
  to = "/"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "*.(css|js|svg|jpg|png)"
  [headers.values]
    Cache-Control = "max-age=604800, public"
[[headers]]
  for = "*.(ttf|ttc|otf|eot|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
